void main() {
  print('Fadil');
}

// COMMIT -> SAVE PERUBAHAN v
// PULL -> DOWNLOAD PERUBAHAN DI BRANCH TERPILIH v
// FETCH -> DOWNLOAD SEMUA BRANCH v
// PUSH -> UPLOAD PERUBAHAN KE REMOTE (GITHUB/GITLAB)